### ISSUE TITLE
maximum downvotes per day 

### ISSUE THREAD

**Issue by AliCihan** [exo-do/nodebb-plugin-reputation-rules#5]
> Rule #4
> 
> One user can't vote (up or down) more than X times a day, being X = reputation/10. With a minimum of 5 and a max of 50

Hello, we do not have a problem with upvotes, but downvote race between two people can be problematic. Can we have another rule like rule#4 for downvotes only? 

Constant downvotes are forbidden verbally in our forum, but this does not work perfectly. 

Thanks.

**Comment by TheBronx** [comment]
We could separate rule number 4 into two rules then, one for upvotes and one for downvotes.
It is easy.

I am curious though, are you using rule number 3? Users who downvote lose reputation too, that should prevent users from downvoting too much unless they don't care about their own reputation.
Also, rule number 6, that limits how many times you can vote (up or down) the same user is meant to prevent a user from voting everything another user posts.

This is just to understand your problem better, to see if there is a better way that we could implement anti-abuse measures.

Thank you!

**Comment by AliCihan** [comment]
member reputation in our forum ranges from -60 to 15.000... Although top a few members are outliers... you can check from here:
https://yesilkartforum.com/forum/

We created a culture in the forum that upvotes and downvotes are used for totally different things... 

* If you share your information or experience and if users find useful, then they will upvote your post... We have 5 different groups based on reputation and you will get stars depending on your reputation level starting from 500 upvotes :) https://yesilkartforum.com/forum/groups
Upvoting is encouraged so people can share more experience...

* But downvoting is only used to cast out trolls... So, if you are damaging the forum atmosphere, or just trying to tease people, then you will be downvoted, but you will not get downvote only because someone disagrees with you. This is verbally forbidden. Trolls do not care about rules but they care when their posts are downvoted and posts get transparent (we use dwnvtr plugin for this)... 

As you can tell, downvoting is encouraged to some extent so we can cast out trolls. 

Here is the abuse, sometimes a person gets angry, usually because someone downvoted them and start serially downvote a particular user; we had this problem happened three times, and I am talking about downvoting several hundreds of votes... As you can tell, this affects the reputation of that user dramatically. 

We have 5 rep limit to be able to downvote someone, but one person who did that abuse had more than 100 reps... So, if people have motivation and time, they can really abuse it :) 

So, you can tell that we do not want to limit upvotes for anyone since some people deserve to be upvoted; and we want everyone to be able to downvote trolls, not only high rep users... (Vast majority of the users are behaving well and they are protecting the forum atmosphere)... That is the reason we cannot use rule 3 and rule 6... 

We haven't observed that upvoting is abused... But we want to limit downvotes 10 times per month for anyone...

**Comment by TheBronx** [comment]
Wow, thanks for the extensive feedback. I will try to implement this in the next few days and release a new version.

**Comment by AliCihan** [comment]
Thanks

**Comment by AliCihan** [comment]
@TheBronx Hello, are these rules affecting admins? or are they immune to these rules?

**Comment by TheBronx** [comment]
They affect everyone.

**Comment by AliCihan** [comment]
Hello, I can close this issue since this feature is added to the NodeBB core settings:

https://github.com/NodeBB/NodeBB/issues/8427
